## Esercizio Uno

__Scrivete codice per creare:__

- Un array unidimensionale di numeri casuali compresi tra 0 e 1;

- Un array bidimensionale di dimensione 3x3 con valori interi casuali.

In [7]:
import numpy as np

__Array unidimensionale a caso__

In [38]:
arr_1d = np.random.random(3)
print(arr_1d)

[0.23833156 0.05219201 0.85505398]


In [27]:
arr_2d= np.random.randint(10,72, size=(3,3))
arr_2d

array([[64, 33, 37],
       [14, 12, 35],
       [50, 61, 34]], dtype=int32)

## Esercizio Due

create uno script per generare 2 array bidimensionali numpy 4x4 con valori interi casuali ed eseguite le seguenti operazioni:

- Restituite la somma di tutti gli elementi dei singoli array che si trovano nell'ultima riga dalla seconda colonna in poi

- Unite i 2 array secondo l'asse 1

In [40]:
arr1 = np.random.randint(0, 100, size=(4,4))
arr2 = np.random.randint(0, 100, size=(4,4))

print("array 1:\n", arr1)
print("array 2:\n", arr2)

array 1:
 [[11 90 82  0]
 [80 72 78 99]
 [18 19 12 50]
 [52 26 61 95]]
array 2:
 [[23 54 68 87]
 [45 98 30 19]
 [92 88 91 72]
 [ 4 19 67 94]]


__Somma tra i due__

- Restituite la somma di tutti gli elementi dei singoli array che si trovano nell'ultima riga dalla seconda colonna in poi


In [41]:
sum1= np.sum(arr1[-1,1:]) #ultima=meno1
sum2= np.sum(arr2[-1,1:]) 

print(sum1)
print(sum2)
print(sum1+sum2)

182
180
362


__Unire con concatenate__

- Unite i 2 array secondo l'asse 1
- Unite i 2 array secondo l'asse 0

In [42]:
arr_con= np.concatenate((arr1, arr2), axis=1)

arr_con

array([[11, 90, 82,  0, 23, 54, 68, 87],
       [80, 72, 78, 99, 45, 98, 30, 19],
       [18, 19, 12, 50, 92, 88, 91, 72],
       [52, 26, 61, 95,  4, 19, 67, 94]], dtype=int32)

In [43]:
arr_con= np.concatenate((arr1, arr2), axis=0)

arr_con

array([[11, 90, 82,  0],
       [80, 72, 78, 99],
       [18, 19, 12, 50],
       [52, 26, 61, 95],
       [23, 54, 68, 87],
       [45, 98, 30, 19],
       [92, 88, 91, 72],
       [ 4, 19, 67, 94]], dtype=int32)

## Esercizio Tre

__Create 1 array unidimensionale con 50 valori randomici compresi tra 1 e 1.000 e fate i seguenti calcoli:__

- Calcolo della media;

- Calcolo della mediana;

- Calcolo della moda;

- Calcolo della deviazione standard;

- Trasformatelo in un array 5 X 10


In [56]:
from scipy import stats

In [57]:
arr = np.random.randint(1,1000, 50)
arr

array([562, 419, 277,  23, 653, 563, 199, 289, 861, 128, 797, 246, 285,
       900, 739, 423, 883, 845, 857, 447, 530, 104, 839, 682, 765, 914,
       268, 597,  22, 195, 223, 706, 465, 933, 979, 489, 346, 426, 436,
       845, 872, 340, 879, 790, 671, 315, 627,  73, 588, 559], dtype=int32)

__Calcolo della media, mediana, moda, deviazione__


In [58]:
media= np.mean(arr)
print(media)

mediana= np.median(arr)
print(mediana)

moda = stats.mode(arr)
print(moda)

dev = np.std(arr)
print(dev)

537.48
560.5
ModeResult(mode=np.int32(845), count=np.int64(2))
273.9837396635063


__Trasformatelo in un array 5 X 10__


In [59]:
arr_mod = arr.reshape((5,10))
print(arr_mod)

[[562 419 277  23 653 563 199 289 861 128]
 [797 246 285 900 739 423 883 845 857 447]
 [530 104 839 682 765 914 268 597  22 195]
 [223 706 465 933 979 489 346 426 436 845]
 [872 340 879 790 671 315 627  73 588 559]]


## Esercizio 4

__Descrizione:__
Crea un array utilizzando linspace, cambia la sua
forma con reshape, genera un array casuale e calcola la somma
degli elementi.

__Esercizio:__

1. Crea un array di 12 numeri equidistanti tra 0 e 1 usando
linspace.


In [72]:
arr_lin = np.linspace(0,1, 12).round(2)
arr_lin

array([0.  , 0.09, 0.18, 0.27, 0.36, 0.45, 0.55, 0.64, 0.73, 0.82, 0.91,
       1.  ])

2. Cambia la forma dell'array a una matrice 3x4.


In [73]:
mat_lin = arr_lin.reshape(3,4)
mat_lin

array([[0.  , 0.09, 0.18, 0.27],
       [0.36, 0.45, 0.55, 0.64],
       [0.73, 0.82, 0.91, 1.  ]])

3. Genera una matrice 3x4 di numeri casuali tra 0 e 1.


In [74]:
mat_random= np.random.random((3,4)).round(2)
mat_random

array([[0.29, 0.98, 0.79, 0.74],
       [0.84, 0.19, 0.92, 0.51],
       [0.15, 0.18, 0.88, 0.34]])

4. Calcola e stampa la somma degli elementi di entrambe le
matrici.

In [77]:
sum_lin = np.sum(mat_lin)
sum_rand = np.sum(mat_random)

print (sum_lin)
print (sum_rand)
print (sum_lin + sum_rand)

6.0
6.81
12.809999999999999


## Esercizio 5

1. Utilizza np.linspace per creare un array di 50 numeri equidistanti tra 0 e 10.

2. Utilizza np.random.random per creare un array di 50 numeri casuali compresi tra 0 e 1.

In [86]:
arr_uno = np.linspace(0,10,50)

arr_due = np.random.random(50)

#print(arr_uno,arr_due)

3. Somma i due array elemento per elemento per ottenere un nuovo array.

4. Calcola la somma totale degli elementi del nuovo array.


In [ ]:
arr_somma = arr_uno + arr_due
print(arr_somma)

som_tot = np.sum(arr_somma)
som_tot

[ 0.04384923  1.19834888  1.24067239  1.53574259  1.41065034  2.015014
  1.81986406  1.91328795  1.6421828   2.52344629  2.23042039  2.44344529
  3.44008336  2.79837173  2.9278225   3.93022885  3.661381    3.47128754
  4.53295323  3.95756098  4.23008172  4.4268415   5.46531454  5.49054099
  4.99933315  5.59816012  5.38379069  5.82167386  6.65353228  6.39956333
  6.77641654  6.69650113  6.89057372  7.00606226  7.0643792   7.65601171
  7.91925755  7.74385324  8.64473528  8.05083988  8.38141033  8.81536494
  8.93128642  8.96048222  9.56959608  9.51752771 10.15319895  9.7141864
 10.18217346 10.02684324]


np.float64(271.9061458246813)

5. Calcola la somma degli elementi del nuovo array che sono maggiori di 5.


In [89]:
piu_5 = np.sum(arr_somma[arr_somma > 5])

piu_5

np.float64(209.51327607327264)

6. Stampa gli array originali, il nuovo array risultante dalla somma e le somme calcolate.


In [93]:

print("\narry uno con linspace:")
print(arr_uno)


print("\narry due con random:")
print(arr_due)


print("\narry risultato somma:")
print(arr_somma)

print(f"\nsomma totale elementi: {som_tot}")
print(f"\nsomma elementi > 5: {piu_5}")




arry uno con linspace:
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]

arry due con random:
[0.04384923 0.99426724 0.83250912 0.92349769 0.59432381 0.99460584
 0.59537426 0.48471652 0.00952974 0.68671159 0.18960406 0.19854733
 0.99110377 0.14531051 0.07067964 0.86900436 0.39607487 0.00189979
 0.85948384 0.08000996 0.14844906 0.14112721 0.97551862 0.79666344
 0.10137396 0.4961193  0.07766824 0.31146978 0.93924657 0.48119598
 0.653967